name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  install-and-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Use Node.js 18
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Lint (ESLint)
        run: npm run lint || (echo "Lint failed" && exit 1)

      - name: Run tests (with coverage)
        run: |
          mkdir -p coverage
          echo "No test coverage data found" > coverage/info.txt
          npm test || (echo "Tests failed" && exit 1)

      - name: Security audit (npm audit)
        run: |
          npm audit --json > audit.json || echo "{}" > audit.json
        continue-on-error: true

      - name: Upload CI Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: ci-artifacts
          path: |
            audit.json
            coverage/**
          if-no-files-found: warn
