name: Release Notes Generator

on:
  push:
    tags:
      - 'v*.*.*' # Example: v1.0.0

jobs:
  release-notes:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Generate release notes
      uses: softprops/action-gh-release@v1
      with:
        generate_release_notes: true
