name: Generate Release Notes

on:
  push:
    tags:
      - 'v*.*.*'
  workflow_dispatch:

jobs:
  release-notes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate release notes
        id: notes
        uses: actions/github-script@v7
        with:
          script: |
            const { execSync } = require('child_process');
            const log = execSync('git log -10 --pretty=format:"- %s (%an)"').toString();
            core.setOutput("notes", `### Recent Changes\n${log}`);

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body: ${{ steps.notes.outputs.notes }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
