name: Scheduled Maintenance Tasks

on:
  schedule:
    - cron: '0 2 * * 0' # Every Sunday at 2 AM (UTC)
  workflow_dispatch:

jobs:
  maintenance:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Run maintenance script
        run: |
          echo "🧹 Running scheduled maintenance..." | tee maintenance-log.txt
          echo "Generating backup timestamp: $(date -u)" >> maintenance-log.txt
          echo "Maintenance completed successfully ✅" >> maintenance-log.txt
          cat maintenance-log.txt

      - name: Upload maintenance log
        uses: actions/upload-artifact@v4
        with:
          name: maintenance-log
          path: maintenance-log.txt
          if-no-files-found: error
